# Generated by Django 3.2.4 on 2021-07-30 03:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('required', models.BooleanField(default=True)),
                ('content', models.TextField(blank=True, default='')),
                ('starting_state', models.CharField(choices=[('locked', '🔒'), ('unlocked', '🔓'), ('ongoing', '🟡'), ('completed', '🟢'), ('perfect', '⭐')], default='locked', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(default='Nouveau Cours', max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('subject', models.CharField(choices=[('in', 'Informatique'), ('ai', 'Intelligence Artificielle'), ('ma', 'Mathématiques'), ('sc', 'Sciences')], max_length=2)),
                ('difficulty', models.CharField(choices=[('1', 'débutant'), ('2', 'facile'), ('3', 'intermédiaire'), ('4', 'avancé'), ('5', 'difficile'), ('6', 'expert')], max_length=1)),
                ('access', models.CharField(choices=[('PU', 'Public'), ('UN', 'Non répertorié'), ('RE', 'Restrain'), ('PR', 'Privé')], default='PR', max_length=2)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='(Sans nom)', max_length=30)),
                ('desc', models.CharField(blank=True, max_length=100)),
                ('hint', models.CharField(blank=True, max_length=50)),
                ('solution', models.CharField(blank=True, max_length=150)),
                ('access', models.CharField(choices=[('PU', 'Public'), ('UN', 'Unlisted'), ('RE', 'Restricted'), ('PR', 'Private')], default='PR', max_length=2)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LevelProgression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('state', models.CharField(choices=[('ongoing', '🟡'), ('completed', '🟢')], max_length=20)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('numero', models.IntegerField()),
                ('question', models.CharField(max_length=200)),
                ('timer', models.CharField(choices=[('15', '15 secondes'), ('30', '30 secondes'), ('45', '45 secondes')], default='30', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField(max_length=200)),
                ('correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationLevelProgression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True)),
                ('solutions', models.TextField(default='[]')),
                ('level_progression', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alive_level_progression', to='playground.levelprogression')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.TextField(default='{}')),
                ('code', models.TextField(default='[]')),
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='playground.level')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('locked', '🔒'), ('unlocked', '🔓'), ('ongoing', '🟡'), ('completed', '🟢'), ('perfect', '⭐')], default='locked', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.course')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(to='playground.Question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(to='playground.Response'),
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(default='Nouvelle classe', max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('subject', models.CharField(choices=[('in', 'Informatique'), ('ai', 'Intelligence Artificielle'), ('ma', 'Mathématiques'), ('sc', 'Sciences')], max_length=2)),
                ('courses', models.ManyToManyField(blank=True, to='playground.Course')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='home.professor')),
                ('students', models.ManyToManyField(blank=True, related_name='classrooms', to='home.Student')),
            ],
        ),
        migrations.CreateModel(
            name='AliveScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('')])),
                ('code', models.TextField(default='# Entrez votre code ci-dessous\n\n')),
                ('access', models.CharField(choices=[('PU', 'Public'), ('UN', 'Unlisted'), ('RE', 'Restricted'), ('PR', 'Private')], default='PR', max_length=2)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityProgression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('state', models.CharField(choices=[('locked', '🔒'), ('unlocked', '🔓'), ('ongoing', '🟡'), ('completed', '🟢'), ('perfect', '⭐')], max_length=20)),
                ('completion', models.FloatField(default=0.0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.activity')),
                ('level_progressions', models.ManyToManyField(blank=True, to='playground.LevelProgression')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='levels',
            field=models.ManyToManyField(blank=True, to='playground.Level'),
        ),
        migrations.AddField(
            model_name='activity',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.section'),
        ),
    ]
