# Generated by Django 3.2 on 2021-05-13 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_alter_question_numero'),
        ('playground', '0002_auto_20210512_1815'),
    ]

    operations = [
    ]
