# Generated by Django 3.1.1 on 2021-05-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_merge_20210512_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='alivechallengeprogression',
            name='solutions',
            field=models.TextField(default='[]'),
        ),
    ]
