# Generated by Django 3.2.4 on 2021-07-03 05:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playground', '0004_alivechallengeprogression_solutions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='access',
            field=models.CharField(choices=[('PU', 'Public'), ('UN', 'Unlisted'), ('RE', 'Restricted'), ('PR', 'Private')], default='PR', max_length=2),
        ),
        migrations.AlterField(
            model_name='level',
            name='access',
            field=models.CharField(choices=[('PU', 'Public'), ('UN', 'Unlisted'), ('RE', 'Restricted'), ('PR', 'Private')], max_length=2),
        ),
        migrations.CreateModel(
            name='AliveScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('')])),
                ('code', models.TextField(default='# Entrez votre code ci-dessous\n\n')),
                ('access', models.CharField(choices=[('PU', 'Public'), ('UN', 'Unlisted'), ('RE', 'Restricted'), ('PR', 'Private')], default='PR', max_length=2)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
