# Generated by Django 3.2.4 on 2021-07-13 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_auto_20210703_0115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
    ]
