# Generated by Django 3.2.4 on 2021-07-13 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_student_courses'),
        ('playground', '0006_delete_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='home.professor'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='classrooms', to='home.Student'),
        ),
    ]
