# Generated by Django 3.2.4 on 2021-07-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_auto_20210703_0115'),
        ('home', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='playground.Course'),
        ),
    ]
